/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2017-10-18 07:09:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html_005fcss;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;

public final class accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t<title>Projet</title>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t<script src=\"main.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.1/jquery.min.js\"></script>\n");
      out.write("\t<link href=\"final.css\" rel=\"stylesheet\">\n");
      out.write("\t<script src=\"js-webshim/minified/polyfiller.js\"></script> \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<header class=\"backGroundHeader\">\n");
      out.write("\t\t<nav class=\"menuAccueilHeader\">\n");
      out.write("\t\t\t<div class=\"containerMenu\">\n");
      out.write("\t\t\t\t<div class=\"logoMenuAccueil\">\n");
      out.write("\t\t\t\t\t<img src=\"images/logo.png\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"lienMenuAccueil\">\n");
      out.write("\t\t\t\t\t<a href=\"inscription.jsp\"><button>CREER UN COMPTE</button></a>\n");
      out.write("\t\t\t\t\t<a href=\"connection.jsp\"><button>SE CONNECTER</button></a>\n");
      out.write("\t\t\t\t\t<a href=\"#\">AIDE</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<div class=\"containerHeader\">\n");
      out.write("\t\t\t<div class=\"pageAccueilRecherche\">\n");
      out.write("\t\t\t\t<h1>Réservez vos billets de train</h1>\n");
      out.write("\t\t\t\t<h3>Voyagez avec nous</h3>\n");
      out.write("\t\t\t\t<div class=\"formulaire_trajet\" >\n");
      out.write("\t\t\t\t\t<form  id=\"form1\">\n");
      out.write("\t\t\t\t\t\t<h1>Votre trajet</h1>\n");
      out.write("\t\t\t\t\t\t<div class=\"champsForm\">\n");
      out.write("\t\t\t\t\t\t\t<input onkeyup=\"search(this)\" onclick=\"search(this)\" id=\"trajet1\" type=\"text\" placeholder=\"Ville de départ\"><br>\n");
      out.write("\t\t\t\t\t\t\t<input onkeyup=\"search(this)\" onclick=\"search(this)\" id=\"trajet2\" type=\"text\" placeholder=\"Ville d'arrivée\"/><br>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"champsForm\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t        \t\t\t<label for=\"min\">Date Départ</label><br>\n");
      out.write("\t\t\t       \t\t\t\t<input class=\"min-today dateDep\" id=\"min\" type=\"date\" placeholder=\"YYYY-MM-DD\" data-date-split-input=\"false\" />\n");
      out.write("\t    \t\t\t\t\t</div>\n");
      out.write("\t    \t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-row\">\n");
      out.write("\t\t\t\t\t\t        <label for=\"min\">Date Arrivé</label><br>\n");
      out.write("\t\t\t\t\t\t        <input class=\"min-today dateArr\" id=\"min\" type=\"date\" placeholder=\"YYYY-MM-DD\" data-date-split-input=\"false\" />\n");
      out.write("\t\t\t\t    \t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"send()\" value=\"Valider\">\n");
      out.write("\t\t\t\t\t\t<span id=\"error\" hidden>Mauvaise entré</span>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"choixRep\" hidden>\n");
      out.write("\t\t\t\t<h1> Les gares</h1>\n");
      out.write("\t\t\t\t<div id=\"liste\">\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t\n");
      out.write("\t<script language=\"JavaScript\">\n");
      out.write("\n");
      out.write("\t\t");

			ArrayList<String> list = new ArrayList<>();
			Connection con=null;
			
			try {
				
				Class.forName("org.postgresql.Driver");
				con = DriverManager.getConnection("jdbc:postgresql://psqlserv/da2i","lamboisa","moi");
//				con = DriverManager.getConnection("jdbc:postgresql://localhost/da2i","lamboisa","moi");
				Statement stmt = con.createStatement();
				
				String query = "SELECT CONCAT_WS('-',nom,ville,gno) FROM gare";
			
				ResultSet rs = stmt.executeQuery(query);
				
				while( rs.next() ){
					list.add(rs.getString(1));
				}
				
			}catch (Exception e) {
				e.printStackTrace();
			}finally{
				try {
					con.close();
				} catch (SQLException e) {
					e.printStackTrace();
				}
			}
		
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\tvar tab=new Array();\n");
      out.write("\t\t\n");
      out.write("\t\t");
 for( int i=0 ; i<list.size() ; i++ ){ 
      out.write("\n");
      out.write("\t\t\ttab[");
      out.print( i );
      out.write("] = \"");
      out.print( list.get(i) );
      out.write("\";\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\tinitDate();\n");
      out.write("\t\t\n");
      out.write("\t\tdocument.onclick = function(e) {\n");
      out.write("\t\t\tif(e.srcElement.id==\"trajet1\" || e.srcElement.id==\"trajet2\"){\n");
      out.write("\t\t\t\tdocument.getElementById(\"choixRep\").hidden=false;\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tdocument.getElementById(\"choixRep\").hidden=true;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\t\n");
      out.write("\t\t\n");
      out.write("\t\tfunction search(object){\n");
      out.write("\t\t\tdocument.getElementById(\"liste\").innerHTML = \"\";\n");
      out.write("\n");
      out.write("\t\t\tvar temp = \"<ul>\";\n");
      out.write("\t\t\ttab.forEach(function(element) {\n");
      out.write("\t\t\t\tif(element.startsWith(object.value)){\n");
      out.write("\t\t\t\t\ttemp = temp + \"<li onclick=\\\"recup(this,\"+object.id+\")\\\"><a>\" +  element.substring(0, element.lastIndexOf(\"-\")) + \"</a></li>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\ttemp = temp + \"</ul>\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(temp).appendTo(document.getElementById(\"liste\"));\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction recup(string,id){\n");
      out.write("\t\t\tdocument.getElementById(id.id).value=string.innerText;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction send(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar idgare1;\n");
      out.write("\t\t\tvar idgare2;\n");
      out.write("\t\t\tvar dateDep = document.getElementsByClassName(\"dateDep\")[0].value;\n");
      out.write("\t\t\tvar dateArr = document.getElementsByClassName(\"dateArr\")[0].value\n");
      out.write("\t\t\t\n");
      out.write("\t\t\ttab.forEach(function(element){\n");
      out.write("\t\t\t\tif( element.includes(document.getElementById(\"trajet1\").value) ){\n");
      out.write("\t\t\t\t\tidgare1 = element.substring(element.lastIndexOf(\"-\")+1);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif( element.includes(document.getElementById(\"trajet2\").value) ){\n");
      out.write("\t\t\t\t\tidgare2 = element.substring(element.lastIndexOf(\"-\")+1);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\tvar dateValide;\n");
      out.write("\t\t\tif( document.getElementById(\"trajet1\").value != \"\" && document.getElementById(\"trajet2\").value != \"\" && dateDep !=\"\" && dateArr !=\"\" && idgare1 != undefined && idgare2 != undefined ){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\twindow.location.href = \"http://localhost:8080/Projet/html_css/temp3.jsp?idgare1=\"+idgare1+\"&idgare2=\"+idgare2+\"&dateDep=\"+dateDep+\"&dateArr=\"+dateArr;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").hidden = false;\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
