/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.46
 * Generated at: 2018-01-11 18:13:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html_005fcss;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import tool.BddTools;

public final class accueil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("tool.BddTools");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\n");
      out.write("\t<title>Projet</title>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"main.js\"></script>\n");
      out.write("\t<script src=\"js-webshim/minified/polyfiller.js\"></script>\n");
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("  \t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("  \t<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("  \t<script type=\"text/javascript\" src=\"picker/src/wickedpicker.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"picker/src/wickedpicker.css\" />\n");
      out.write("\n");
      out.write("\t<link href=\"final.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<header class=\"backGroundHeader\">\n");
      out.write("\t\t<nav class=\"menuAccueilHeader\">\n");
      out.write("\t\t\t<div class=\"containerMenu\">\n");
      out.write("\t\t\t\t<div class=\"logoMenuAccueil\">\n");
      out.write("\t\t\t\t\t<a href=\"accueil.jsp\"><img src=\"images/logo.png\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"lienMenuAccueil\">\n");
      out.write("\t\t");
 if(session.getAttribute("id_client") == null ){ 
      out.write("\n");
      out.write("\t\t\t\t\t<a href=\"inscription.jsp\"><button>CREER UN COMPTE</button></a>\n");
      out.write("\t\t\t\t\t<a href=\"connection.jsp?page=accueil\"><button>SE CONNECTER</button></a>\n");
      out.write("\t\t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t\t\t<a href=\".././servlet/Panier\"><button>MON PANIER</button></a>\n");
      out.write("\t\t\t\t\t<a href=\".././servlet/Deconnexion?page=accueil\"><button>DECONNECTION</button></a>\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<div class=\"containerHeader\">\n");
      out.write("\t\t\t<div class=\"pageAccueilRecherche\">\n");
      out.write("\t\t\t\t<h1>Réservez vos billets de train</h1>\n");
      out.write("\t\t\t\t<h3>Voyagez avec nous</h3>\n");
      out.write("\t\t\t\t<div class=\"formulaire_trajet\" >\n");
      out.write("\t\t\t\t\t<form>\n");
      out.write("\t\t\t\t\t\t<h1>Votre trajet</h1>\n");
      out.write("\t\t\t\t\t\t<div class=\"champsForm\">\n");
      out.write("\t\t\t\t\t\t\t<input onkeyup=\"search(this)\" onclick=\"search(this)\" id=\"trajet1\" type=\"text\" placeholder=\"Ville de départ\"><br>\n");
      out.write("\t\t\t\t\t\t\t<input onkeyup=\"search(this)\" onclick=\"search(this)\" id=\"trajet2\" type=\"text\" placeholder=\"Ville d'arrivée\"/><br>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t<label>Date : </label>\n");
      out.write("\t                \t\t\t<div>\n");
      out.write("\t                    \t\t\t<input type=\"text\" id=\"datepicker\">\n");
      out.write("\t                \t\t\t</div>\n");
      out.write("\t           \t\t\t\t</div>\n");
      out.write("\t           \t\t\t\t<SELECT id=\"select\" name=\"avant_apres\" size=\"1\">\n");
      out.write("\t                \t\t\t<option value=\"0\" >Partir après\n");
      out.write("\t                \t\t\t<option value=\"1\" >Arrivee après\n");
      out.write("\t                \t\t\t<option value=\"2\" >Partir avant\n");
      out.write("\t                \t\t\t<option value=\"3\" >Arrivee avant\n");
      out.write("                \t\t\t</SELECT>\n");
      out.write("                \t\t\t<div class=\"form-group\">\n");
      out.write("                \t\t\t\t<label>Heure : </label>\n");
      out.write("\t                \t\t\t<div>\n");
      out.write("\t                    \t\t\t<input type=\"text\" id=\"timepicker\">\n");
      out.write("\t                \t\t\t</div>\n");
      out.write("\t           \t\t\t\t</div>\n");
      out.write("                \t\t</div>\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" onclick=\"send()\" value=\"Valider\">\n");
      out.write("\t\t\t\t\t\t<span id=\"error\" hidden>Mauvaise entré</span>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"choixRep\" hidden>\n");
      out.write("\t\t\t\t\t<h1> Les gares</h1>\n");
      out.write("\t\t\t\t\t<div id=\"liste\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<script language=\"JavaScript\">\n");
      out.write("\t  \n");
      out.write("\t\tvar dateNow = new Date();\n");
      out.write("\t\t$('#timepicker').wickedpicker({\n");
      out.write("\t\t\t twentyFour: true,\n");
      out.write("\t\t\t title: 'Heure',\n");
      out.write("\t\t\t now: '0:00'\n");
      out.write("\t\t});\n");
      out.write("\t    $(\"#datepicker\").datepicker({\n");
      out.write("\t    \tfirstDay: 1,\n");
      out.write("\t    \tmonthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],\n");
      out.write("\t    \tdayNamesMin: ['D','L', 'M', 'M', 'J', 'V', 'S'],\n");
      out.write("\t    \tweekHeader: 'Sem.',\n");
      out.write("\t    \tdateFormat: 'yy-mm-dd',\n");
      out.write("\t        minDate: dateNow\n");
      out.write("\t    });\n");
      out.write("\n");
      out.write("\t\t");

			ArrayList<ArrayList<String>> list = null;
			BddTools t = null;

			try {

        t = new BddTools("da2i");
        list = t.getRequest("SELECT DISTINCT name FROM stops ORDER BY name");

			}catch(Exception e) {
    	   e.printStackTrace();
    	}finally{
    	   t.fermer();
    	}

		
      out.write("\n");
      out.write("\n");
      out.write("\t\tvar tab=new Array();\n");
      out.write("\n");
      out.write("\t\t");
 for( int i=0 ; i<list.size() ; i++ ){ 
      out.write("\n");
      out.write("\t     tab[");
      out.print( i );
      out.write("] = \"");
      out.print( list.get(i).get(0) );
      out.write("\";\n");
      out.write("\t\t");
 } 
      out.write("\n");
      out.write("\n");
      out.write("\t\tdocument.onclick = function(e) {\n");
      out.write("\t\t\tif(e.srcElement.id==\"trajet1\" || e.srcElement.id==\"trajet2\"){\n");
      out.write("\t\t\t\tdocument.getElementById(\"choixRep\").hidden=false;\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\tdocument.getElementById(\"choixRep\").hidden=true;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction search(object){\n");
      out.write("\t\t\tdocument.getElementById(\"liste\").innerHTML = \"\";\n");
      out.write("\n");
      out.write("\t\t\tvar temp = \"<ul>\";\n");
      out.write("\t\t\ttab.forEach(function(element) {\n");
      out.write("\t\t\t\tif(element.includes(object.value)){\n");
      out.write("\t\t\t\t\ttemp = temp + \"<li onclick=\\\"recup(this,\"+object.id+\")\\\"><a>\" + element + \"</a></li>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\ttemp = temp + \"</ul>\";\n");
      out.write("\n");
      out.write("\t\t\t$(temp).appendTo(document.getElementById(\"liste\"));\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction send(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar value1 = null;\n");
      out.write("\t\t\tvar value2 = null;\n");
      out.write("\t\t\tvar temps = replaceAll(document.getElementById(\"timepicker\").value,\" \",\"\");\n");
      out.write("\t\t\tvar select = document.getElementById( \"select\" );\n");
      out.write("\t\t\tselect = ( select.options[ select.selectedIndex ].value );\n");
      out.write("\n");
      out.write("\t\t\ttab.forEach(function(element){\n");
      out.write("\t\t\t\tif(element.valueOf() == (document.getElementById(\"trajet1\").value).valueOf()){\n");
      out.write("\t\t\t\t\tvalue1 = element;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tif(element.valueOf() == (document.getElementById(\"trajet2\").value).valueOf()){\n");
      out.write("\t\t\t\t\tvalue2 = element;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\tif( value1 != \"\" && value2 != \"\" && value1 != null && value2 != null && document.getElementById(\"datepicker\").value != \"\"){\n");
      out.write("\t\t\t\tvar date = new Date(document.getElementById(\"datepicker\").value);\n");
      out.write("\t\t\t\tdate.setSeconds(00);\n");
      out.write("\t\t\t\tdocument.location.href=\".././servlet/Search?date=\"+date.toLocaleString(\"fr-FR\", {hour12: false})+\"&gare1=\"+value1+\"&gare2=\"+value2+\"&temps=\"+temps+\"&select=\"+select;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t}else{\n");
      out.write("\n");
      out.write("\t\t\t\tdocument.getElementById(\"error\").hidden = false;\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction replaceAll(str, find, replace) {\n");
      out.write("\t\t    return str.replace(new RegExp(find, 'g'), replace);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
